### ISSUE TITLE
vim-lsc, omnifunc, surprising completion suggestions

### ISSUE THREAD

**Issue by awelzel** [bbannier/zeek-language-server#60]
Running 0.20 and typing `c$ori<Ctrl+x+o>` for omni-complete in vim-lsc when setting omnifunc to `lsc#complete#complete` yields surprising results. It should yield `orig` minimally as the first result as the `c: connection` object has an orig field. Completing `c$orig$siz` should also suggest `size`

```
" .vimrc snippet
let g:lsc_auto_map = {
  \ 'defaults': v:true,
  \ 'Completion': 'omnifunc',
  \}
```

```
event zeek_init() {
        local c: connection;
        c$orig$size = 1;
        print c$orig$size;
}
```

![Screenshot-20221124-175842](https://user-images.githubusercontent.com/2100509/203836969-acf5345b-6886-40ed-a7d1-775ad56922d8.png)
![Screenshot-20221124-175831](https://user-images.githubusercontent.com/2100509/203836971-76c70cb1-c81e-4fc5-bfce-ec8b0b347f1b.png)
![Screenshot-20221124-175810](https://user-images.githubusercontent.com/2100509/203836974-e1f606cc-4104-4b1f-95b3-0433a0f6a3f7.png)

**Comment by bbannier** [comment]
For field completion we have special handling if the completion was due to a trigger character like `$` which [we register with the client](https://github.com/bbannier/zeek-language-server/blob/0c51f657e4c21f84a95b1715cd9886e823ff9ed7/src/lsp.rs#L312). For item completion we (currently hardcode the assumption that the client does send a `CompletionContext` with the trigger character)[https://github.com/bbannier/zeek-language-server/blob/0c51f657e4c21f84a95b1715cd9886e823ff9ed7/src/lsp.rs#L835], but at least the version of vim-lsc I tried did not support sending this and also announces this on registration (`None` sent for `contextSupport` [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionClientCapabilities)).

The fix is probably to implement the [`TODO`](https://github.com/bbannier/zeek-language-server/blob/0c51f657e4c21f84a95b1715cd9886e823ff9ed7/src/lsp.rs#L835).

**Comment by awelzel** [comment]
I've just tested this and the `c$or` and the completions offered now contain `orig` as the first result. Nice!

However, typing `c$orig$si` does not provide  `size`, even though the `orig: endpoint` has a size attribute.

Also, the following does not complete size:
```
local orig = c$orig;
print orig$si...
```

Putting the type on `orig` does then properly complete to `size`:
```
local orig: endpoint = c$orig;
print orig$si... # < this completes to size
```

Want a new ticket, or re-open tihs one?

**Comment by bbannier** [comment]
> However, typing c$orig$si does not provide size, even though the orig: endpoint has a size attribute.

This definitely is a bug.

> Also, the following does not complete size:
>
> ```
> local orig = c$orig;
> print orig$si...
> ```
> 
> Putting the type on orig does then properly complete to size:
> 
> ```
> local orig: endpoint = c$orig;
> print orig$si... # < this completes to size
> ```
> 
> Want a new ticket, or re-open tihs one?

Yes, also a bug, probably different.
