### ISSUE TITLE
Completions after :: not working

### ISSUE THREAD

**Issue by awelzel** [bbannier/zeek-language-server#71]
Hey, another one around completions (0.23, vim-lsc, omnifunc CTRL+xo)

Doing the following does not complete to `Intel::read_files`.
```
@load base/frameworks/intel

redef Intel::r<Ctrl+xo>... 
```
Requesting completions after the `::` offers nothing that seems related to `Intel`:
![Screenshot-20221129-111322](https://user-images.githubusercontent.com/2100509/204501856-c691fefc-46a5-436e-b487-522538374e69.png)

Further, might be different, but somehow related, would expect `Intel::Item` as completion, but offers "anything" ?
```
event zeek_init() {
  local item: Intel::It<Ctrl+xo>`
}
```

![Screenshot-20221129-111516](https://user-images.githubusercontent.com/2100509/204502206-aff6ab4b-6e01-4172-bd53-0fade4b69a07.png)

**Comment by bbannier** [comment]
I closed this since pushed a series of patches in #228 which somewhat improve the experience around completing modules or module identifiers. Since neither my forked grammar nor the "official" upstream one directly expose a possible module name of identifiers, everything I did over there happened in postprocessing.
